/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CartRouteImport } from './routes/cart'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RecommendRouteImport } from './routes/recommend'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TopRatedRouteImport } from './routes/top-rated'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as ApiRecommendationsRouteImport } from './routes/api/recommendations'
import { Route as BookBookIdRouteImport } from './routes/book.$bookId'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as DiscoverIndexRouteImport } from './routes/discover.index'
import { Route as DiscoverCategoriesRouteImport } from './routes/discover.categories'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendRoute = RecommendRouteImport.update({
  id: '/recommend',
  path: '/recommend',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TopRatedRoute = TopRatedRouteImport.update({
  id: '/top-rated',
  path: '/top-rated',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecommendationsRoute = ApiRecommendationsRouteImport.update({
  id: '/api/recommendations',
  path: '/api/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const BookBookIdRoute = BookBookIdRouteImport.update({
  id: '/book/$bookId',
  path: '/book/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverIndexRoute = DiscoverIndexRouteImport.update({
  id: '/discover/',
  path: '/discover/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverCategoriesRoute = DiscoverCategoriesRouteImport.update({
  id: '/discover/categories',
  path: '/discover/categories',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/chat': typeof ChatRoute
  '/checkout': typeof CheckoutRoute
  '/community': typeof CommunityRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/recommend': typeof RecommendRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/top-rated': typeof TopRatedRoute
  '/wishlist': typeof WishlistRoute
  '/api/recommendations': typeof ApiRecommendationsRoute
  '/book/$bookId': typeof BookBookIdRoute
  '/category/$slug': typeof CategorySlugRoute
  '/discover/categories': typeof DiscoverCategoriesRoute
  '/discover/': typeof DiscoverIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/chat': typeof ChatRoute
  '/checkout': typeof CheckoutRoute
  '/community': typeof CommunityRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/recommend': typeof RecommendRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/top-rated': typeof TopRatedRoute
  '/wishlist': typeof WishlistRoute
  '/api/recommendations': typeof ApiRecommendationsRoute
  '/book/$bookId': typeof BookBookIdRoute
  '/category/$slug': typeof CategorySlugRoute
  '/discover/categories': typeof DiscoverCategoriesRoute
  '/discover': typeof DiscoverIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/chat': typeof ChatRoute
  '/checkout': typeof CheckoutRoute
  '/community': typeof CommunityRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/recommend': typeof RecommendRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/top-rated': typeof TopRatedRoute
  '/wishlist': typeof WishlistRoute
  '/api/recommendations': typeof ApiRecommendationsRoute
  '/book/$bookId': typeof BookBookIdRoute
  '/category/$slug': typeof CategorySlugRoute
  '/discover/categories': typeof DiscoverCategoriesRoute
  '/discover/': typeof DiscoverIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cart'
    | '/chat'
    | '/checkout'
    | '/community'
    | '/login'
    | '/orders'
    | '/profile'
    | '/recommend'
    | '/search'
    | '/settings'
    | '/signup'
    | '/top-rated'
    | '/wishlist'
    | '/api/recommendations'
    | '/book/$bookId'
    | '/category/$slug'
    | '/discover/categories'
    | '/discover/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/cart'
    | '/chat'
    | '/checkout'
    | '/community'
    | '/login'
    | '/orders'
    | '/profile'
    | '/recommend'
    | '/search'
    | '/settings'
    | '/signup'
    | '/top-rated'
    | '/wishlist'
    | '/api/recommendations'
    | '/book/$bookId'
    | '/category/$slug'
    | '/discover/categories'
    | '/discover'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cart'
    | '/chat'
    | '/checkout'
    | '/community'
    | '/login'
    | '/orders'
    | '/profile'
    | '/recommend'
    | '/search'
    | '/settings'
    | '/signup'
    | '/top-rated'
    | '/wishlist'
    | '/api/recommendations'
    | '/book/$bookId'
    | '/category/$slug'
    | '/discover/categories'
    | '/discover/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CartRoute: typeof CartRoute
  ChatRoute: typeof ChatRoute
  CheckoutRoute: typeof CheckoutRoute
  CommunityRoute: typeof CommunityRoute
  LoginRoute: typeof LoginRoute
  OrdersRoute: typeof OrdersRoute
  ProfileRoute: typeof ProfileRoute
  RecommendRoute: typeof RecommendRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  TopRatedRoute: typeof TopRatedRoute
  WishlistRoute: typeof WishlistRoute
  ApiRecommendationsRoute: typeof ApiRecommendationsRoute
  BookBookIdRoute: typeof BookBookIdRoute
  CategorySlugRoute: typeof CategorySlugRoute
  DiscoverCategoriesRoute: typeof DiscoverCategoriesRoute
  DiscoverIndexRoute: typeof DiscoverIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommend': {
      id: '/recommend'
      path: '/recommend'
      fullPath: '/recommend'
      preLoaderRoute: typeof RecommendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/top-rated': {
      id: '/top-rated'
      path: '/top-rated'
      fullPath: '/top-rated'
      preLoaderRoute: typeof TopRatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recommendations': {
      id: '/api/recommendations'
      path: '/api/recommendations'
      fullPath: '/api/recommendations'
      preLoaderRoute: typeof ApiRecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$bookId': {
      id: '/book/$bookId'
      path: '/book/$bookId'
      fullPath: '/book/$bookId'
      preLoaderRoute: typeof BookBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover/': {
      id: '/discover/'
      path: '/discover'
      fullPath: '/discover/'
      preLoaderRoute: typeof DiscoverIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover/categories': {
      id: '/discover/categories'
      path: '/discover/categories'
      fullPath: '/discover/categories'
      preLoaderRoute: typeof DiscoverCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CartRoute: CartRoute,
  ChatRoute: ChatRoute,
  CheckoutRoute: CheckoutRoute,
  CommunityRoute: CommunityRoute,
  LoginRoute: LoginRoute,
  OrdersRoute: OrdersRoute,
  ProfileRoute: ProfileRoute,
  RecommendRoute: RecommendRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  TopRatedRoute: TopRatedRoute,
  WishlistRoute: WishlistRoute,
  ApiRecommendationsRoute: ApiRecommendationsRoute,
  BookBookIdRoute: BookBookIdRoute,
  CategorySlugRoute: CategorySlugRoute,
  DiscoverCategoriesRoute: DiscoverCategoriesRoute,
  DiscoverIndexRoute: DiscoverIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
